name: budget_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.10.1

dependencies:
  data_table_2: ^2.7.2
  excel: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  timezone: ^0.10.1
  uuid: ^4.5.2
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  linux:
    generate: true
    image_path: "assets/image/logo.png"
  macos:
    generate: true
    image_path: "assets/image/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/image/
